<template>
  <div class="h-full">
    <img src="/images/about.jpeg" alt="sai-property" class="w-full h-[30vh] object-cover">
      <div class="max-w-5xl mx-auto py-12">
        <h2 class="font-bold my-4">Privacy Policy</h2>

        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells Youabout Your privacy rights and how the law protects You.</p>
        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

        <h2 class="font-bold my-4">For the purposes of this Privacy Policy:</h2>

        <ul class="my-4 px-5 list-disc">
            <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
            <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to AVGEstate, Sushma Infinium, Zirakpur</li>
            <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li>Country refers to: Punjab, India</li>
            <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
            <li>Service refers to the Website.</li>
            <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)</li>
        </ul>

        <h2 class="font-bold my-4 text-xl">Collecting and Using Your Personal Data</h2>

        <h3 class="font-bold my-4">Types of Data Collected</h3>

        <strong class="my-4">Personal Data</strong>

        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.Personally identifiable information may include, but is not limited to:</p>

        <ul class="my-4 px-5 list-disc">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Usage Data</li>
        </ul>

        <h3 class="font-bold my-4">Changes to this Privacy Policy </h3>

        <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
        <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes.Changes to this Privacy Policy are effective when they are posted on this page.</p>

      </div>
  </div>
</template>

<script setup>

</script>

<style scoped>
  h2{
    font-size: 18px;
    font-weight: bold;
    margin-bottom: 6px;
    margin-top: 2em;
  }
  p{
    font-size: 14px;
    color: #DCDCDC;
  }
</style>